import json
import io
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from typing import List
from database import QAItem, QuestionnaireRun


def export_to_docx(run: QuestionnaireRun, qa_items: List[QAItem]) -> bytes:
    """
    Export questionnaire answers to a DOCX file.
    Preserves original question order, inserts answers + citations below each question.
    """
    doc = Document()
    
    # --- Title ---
    title = doc.add_heading(f"Questionnaire Answers", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Subtitle with metadata
    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run_info = meta.add_run(f"Source: {run.filename}  |  Generated by Learnly QA Tool")
    run_info.font.size = Pt(10)
    run_info.font.color.rgb = RGBColor(0x88, 0x88, 0x88)
    
    # --- Coverage Summary ---
    doc.add_heading("Coverage Summary", level=2)
    summary_table = doc.add_table(rows=1, cols=3)
    summary_table.style = 'Table Grid'
    
    hdr = summary_table.rows[0].cells
    hdr[0].text = f"Total Questions: {run.total_questions}"
    hdr[1].text = f"Answered with Citations: {run.answered_count}"
    hdr[2].text = f"Not Found: {run.not_found_count}"
    
    for cell in hdr:
        for para in cell.paragraphs:
            for run_obj in para.runs:
                run_obj.font.bold = True
                run_obj.font.size = Pt(10)
    
    doc.add_paragraph()
    doc.add_heading("Questions & Answers", level=2)
    doc.add_paragraph()
    
    # --- Questions & Answers ---
    for item in sorted(qa_items, key=lambda x: x.question_number):
        # Question
        q_para = doc.add_paragraph()
        q_label = q_para.add_run(f"Q{item.question_number}. ")
        q_label.font.bold = True
        q_label.font.size = Pt(12)
        q_label.font.color.rgb = RGBColor(0x1a, 0x56, 0xdb)  # Blue
        
        q_text = q_para.add_run(item.question_text)
        q_text.font.bold = True
        q_text.font.size = Pt(12)
        
        # Answer
        a_para = doc.add_paragraph()
        a_label = a_para.add_run("Answer: ")
        a_label.font.bold = True
        a_label.font.size = Pt(11)
        
        answer_text = item.answer or "Not found in references."
        a_content = a_para.add_run(answer_text)
        a_content.font.size = Pt(11)
        
        if item.not_found:
            a_content.font.color.rgb = RGBColor(0xcc, 0x44, 0x44)  # Red for not found
        
        # Confidence score
        if not item.not_found and item.confidence_score:
            conf_para = doc.add_paragraph()
            conf_label = conf_para.add_run("Confidence: ")
            conf_label.font.bold = True
            conf_label.font.size = Pt(10)
            conf_label.font.color.rgb = RGBColor(0x55, 0x55, 0x55)
            
            pct = int(item.confidence_score * 100)
            if pct >= 80:
                color = RGBColor(0x16, 0xa3, 0x4a)  # Green
            elif pct >= 50:
                color = RGBColor(0xd9, 0x77, 0x06)  # Amber
            else:
                color = RGBColor(0xcc, 0x44, 0x44)  # Red
            
            conf_val = conf_para.add_run(f"{pct}%")
            conf_val.font.size = Pt(10)
            conf_val.font.color.rgb = color
        
        # Evidence snippet
        if item.evidence_snippet and not item.not_found:
            ev_para = doc.add_paragraph()
            ev_label = ev_para.add_run("Evidence: ")
            ev_label.font.bold = True
            ev_label.font.size = Pt(10)
            ev_label.font.color.rgb = RGBColor(0x55, 0x55, 0x55)
            
            ev_content = ev_para.add_run(f'"{item.evidence_snippet}"')
            ev_content.font.size = Pt(10)
            ev_content.font.italic = True
            ev_content.font.color.rgb = RGBColor(0x44, 0x44, 0x44)
        
        # Citations
        if item.citations:
            try:
                citations = json.loads(item.citations) if isinstance(item.citations, str) else item.citations
            except Exception:
                citations = [item.citations]
            
            if citations:
                cite_para = doc.add_paragraph()
                cite_label = cite_para.add_run("Citations: ")
                cite_label.font.bold = True
                cite_label.font.size = Pt(10)
                cite_label.font.color.rgb = RGBColor(0x55, 0x55, 0x55)
                
                cite_text = cite_para.add_run(" | ".join(citations))
                cite_text.font.size = Pt(10)
                cite_text.font.color.rgb = RGBColor(0x22, 0x56, 0x99)
                cite_text.font.italic = True
        
        # Edited marker
        if item.is_edited:
            edit_para = doc.add_paragraph()
            edit_run = edit_para.add_run("✎ Manually edited")
            edit_run.font.size = Pt(9)
            edit_run.font.color.rgb = RGBColor(0x88, 0x88, 0x88)
            edit_run.font.italic = True
        
        # Separator
        doc.add_paragraph("─" * 60)
    
    # Footer note
    doc.add_paragraph()
    footer = doc.add_paragraph()
    footer_run = footer.add_run("Generated by Learnly Questionnaire Answering Tool · Powered by Claude AI")
    footer_run.font.size = Pt(9)
    footer_run.font.color.rgb = RGBColor(0xaa, 0xaa, 0xaa)
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Save to bytes
    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.read()
